### ISSUE TITLE
How do I use this ？Could you give some Demo Web project?

### ISSUE THREAD

**Issue by liminany** [Pathoschild/webapi.nhibernate-odata#6]
How do I use this source？Could you give some Demo Web project?

Tks！

**Comment by cdroulers** [comment]
I'll create a small sample today!

**Comment by cdroulers** [comment]
Hi @liminany. I've just created pull request #7. Is it clear enough for you? Any comments welcome, I'll update it before merging it.

**Comment by liminany** [comment]
@cdroulers,Tks,I got the codes already.It's enough.
