### ISSUE TITLE
Issue with $count and $expand and nullables

### ISSUE THREAD

**Issue by Benjamin-Berry** [Pathoschild/webapi.nhibernate-odata#9]
I have and error when $count is used. I can use the $expand without the $count or the $count without the $expand. It looks to me like the nullable rewrite isn't occurring.

nhibernate 4.1.0.4000
odata 5.8.1.0

This is the expression without the count

http://localhost:60220/core/Events/?$filter=Number ne 0 and Participants/any(entity:entity/Contact/ContactId eq 20398) 

here it is when the count is used

http://localhost:60220/core/Events/$count?$filter=Number ne 0 and Participants/any(entity:entity/Contact/ContactId eq 20398) 

Here's the two expression dumps.

[count and expand.txt](https://github.com/Pathoschild/webapi.nhibernate-odata/files/1201072/count.and.expand.txt)

It also occurs when the expand results in a list

http://localhost:60220/core/EventStates?$filter=StateType/StateTypeId eq 5&$top=2&$expand=Event($expand=SubGroup,EventType,EventStates)

[expand list.txt](https://github.com/Pathoschild/webapi.nhibernate-odata/files/1201070/expand.list.txt)

**Comment by Benjamin-Berry** [comment]
Confirmed fixed with latest nuget 0.6.0

**Comment by cdroulers** [comment]
Yayyyy!
